/** Service layer barrel. UI imports services from here, never the mocks. */
export { dashboardService } from './dashboard.service'
export { machinesService } from './machines.service'
export { strategiesService } from './strategies.service'
export { tradesService } from './trades.service'
export { alertsService } from './alerts.service'
export { analyticsService } from './analytics.service'
export { brokersService } from './brokers.service'
export { accountsService } from './accounts.service'
export { executionService } from './execution.service'
export { riskService } from './risk.service'
export { eventsService } from './events.service'
export { logsService } from './logs.service'
export { settingsService } from './settings.service'
export { realtime } from './realtime/socket'
export type { RealtimeMessage } from './realtime/types'
export { USE_MOCK } from './api/client'
