"""initial telemetry schema

Revision ID: e1fd66220c23
Revises: 
Create Date: 2026-06-28 20:39:37.270530
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1fd66220c23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('envelope_id', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_category', ['category'], unique=False)
        batch_op.create_index('ix_events_machine_id', ['machine_id'], unique=False)
        batch_op.create_index('ix_events_time', ['time'], unique=False)
        batch_op.create_index('uq_events_envelope_id', ['envelope_id'], unique=True)

    op.create_table('ingest_dedup',
    sa.Column('envelope_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('envelope_id')
    )
    op.create_table('logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('envelope_id', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('logger', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index('ix_logs_machine_id', ['machine_id'], unique=False)
        batch_op.create_index('ix_logs_source_time', ['source', 'time'], unique=False)
        batch_op.create_index('ix_logs_time', ['time'], unique=False)
        batch_op.create_index('uq_logs_envelope_id', ['envelope_id'], unique=True)

    op.create_table('machines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cpu', sa.Float(), nullable=False),
    sa.Column('ram', sa.Float(), nullable=False),
    sa.Column('disk', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('internet_ms', sa.Float(), nullable=False),
    sa.Column('broker_ping_ms', sa.Float(), nullable=False),
    sa.Column('python_status', sa.String(), nullable=False),
    sa.Column('uptime_sec', sa.Integer(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strategy_count', sa.Integer(), nullable=False),
    sa.Column('live', sa.Boolean(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_index('ix_machines_last_heartbeat', ['last_heartbeat'], unique=False)
        batch_op.create_index('ix_machines_live', ['live'], unique=False)
        batch_op.create_index('ix_machines_status', ['status'], unique=False)

    op.create_table('metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('envelope_id', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('machine', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('envelope_id', 'name', name='uq_metrics_envelope_name')
    )
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.create_index('ix_metrics_machine_time', ['machine_id', 'time'], unique=False)
        batch_op.create_index('ix_metrics_name_time', ['name', 'time'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('envelope_id', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('machine', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('broker', sa.String(), nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('entry', sa.Float(), nullable=False),
    sa.Column('exit', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('duration_sec', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index('ix_trades_machine_id', ['machine_id'], unique=False)
        batch_op.create_index('ix_trades_status', ['status'], unique=False)
        batch_op.create_index('ix_trades_strategy', ['strategy'], unique=False)
        batch_op.create_index('ix_trades_symbol', ['symbol'], unique=False)
        batch_op.create_index('ix_trades_time', ['time'], unique=False)
        batch_op.create_index('uq_trades_envelope_id', ['envelope_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index('uq_trades_envelope_id')
        batch_op.drop_index('ix_trades_time')
        batch_op.drop_index('ix_trades_symbol')
        batch_op.drop_index('ix_trades_strategy')
        batch_op.drop_index('ix_trades_status')
        batch_op.drop_index('ix_trades_machine_id')

    op.drop_table('trades')
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_metrics_name_time')
        batch_op.drop_index('ix_metrics_machine_time')

    op.drop_table('metrics')
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index('ix_machines_status')
        batch_op.drop_index('ix_machines_live')
        batch_op.drop_index('ix_machines_last_heartbeat')

    op.drop_table('machines')
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index('uq_logs_envelope_id')
        batch_op.drop_index('ix_logs_time')
        batch_op.drop_index('ix_logs_source_time')
        batch_op.drop_index('ix_logs_machine_id')

    op.drop_table('logs')
    op.drop_table('ingest_dedup')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('uq_events_envelope_id')
        batch_op.drop_index('ix_events_time')
        batch_op.drop_index('ix_events_machine_id')
        batch_op.drop_index('ix_events_category')

    op.drop_table('events')
    # ### end Alembic commands ###
