from __future__ import annotations

from typing import Protocol
from uuid import UUID

from algo_platform.modules.identity.domain.users import (
    ApiKey,
    AuthSession,
    EmailToken,
    EmailTokenPurpose,
    RefreshToken,
    User,
)
from algo_platform.shared.domain.types import UserId


class UserRepository(Protocol):
    async def add(self, user: User) -> None: ...

    async def get(self, user_id: UserId) -> User | None: ...

    async def get_by_email(self, email: str) -> User | None: ...

    async def save(self, user: User) -> None: ...


class SessionRepository(Protocol):
    async def add(self, session: AuthSession) -> None: ...

    async def get(self, session_id: UUID) -> AuthSession | None: ...

    async def list_active_for_user(self, user_id: UserId) -> list[AuthSession]: ...

    async def save(self, session: AuthSession) -> None: ...

    async def revoke_all_for_user(self, user_id: UserId, *, except_session: UUID | None) -> int: ...


class RefreshTokenRepository(Protocol):
    async def add(self, token: RefreshToken) -> None: ...

    async def get_by_hash(self, token_hash: str) -> RefreshToken | None: ...

    async def get_by_hash_for_update(self, token_hash: str) -> RefreshToken | None: ...

    async def save(self, token: RefreshToken) -> None: ...

    async def revoke_family(self, family_id: UUID) -> int: ...

    async def revoke_for_session(self, session_id: UUID) -> int: ...


class EmailTokenRepository(Protocol):
    async def add(self, token: EmailToken) -> None: ...

    async def get_by_hash(
        self, token_hash: str, purpose: EmailTokenPurpose
    ) -> EmailToken | None: ...

    async def save(self, token: EmailToken) -> None: ...

    async def invalidate_for_user(self, user_id: UserId, purpose: EmailTokenPurpose) -> None: ...


class ApiKeyRepository(Protocol):
    async def add(self, key: ApiKey) -> None: ...

    async def get(self, key_id: UUID) -> ApiKey | None: ...

    async def get_by_hash(self, key_hash: str) -> ApiKey | None: ...

    async def list_for_organization(self, organization_id: UUID) -> list[ApiKey]: ...

    async def save(self, key: ApiKey) -> None: ...
