"""NSE F&O universe: sector classification and Yahoo symbol mapping.

NSE's pre-open feed lists every F&O stock but carries no industry, so the
sector used for heatmap grouping comes from this table. A symbol missing here
is still shown - under "Other" - never dropped. Membership itself always comes
from NSE; this table only labels.
"""

from __future__ import annotations

_SECTORS: dict[str, tuple[str, ...]] = {
    "Banks": (
        "AUBANK",
        "AXISBANK",
        "BANDHANBNK",
        "BANKBARODA",
        "BANKINDIA",
        "CANBK",
        "FEDERALBNK",
        "HDFCBANK",
        "ICICIBANK",
        "IDFCFIRSTB",
        "INDIANB",
        "INDUSINDBK",
        "KOTAKBANK",
        "MAHABANK",
        "PNB",
        "RBLBANK",
        "SBIN",
        "UNIONBANK",
        "YESBANK",
    ),
    "Financial Services": (
        "360ONE",
        "ABCAPITAL",
        "ANGELONE",
        "BAJAJFINSV",
        "BAJAJHLDNG",
        "BAJFINANCE",
        "BSE",
        "CAMS",
        "CDSL",
        "CHOLAFIN",
        "HDFCAMC",
        "IEX",
        "IREDA",
        "IRFC",
        "JIOFIN",
        "KFINTECH",
        "LICHSGFIN",
        "LTF",
        "MANAPPURAM",
        "MCX",
        "MOTILALOFS",
        "MUTHOOTFIN",
        "NAM-INDIA",
        "PAYTM",
        "PFC",
        "PNBHOUSING",
        "POLICYBZR",
        "RECLTD",
        "SBICARD",
        "SHRIRAMFIN",
    ),
    "Insurance": ("HDFCLIFE", "ICICIGI", "ICICIPRULI", "LICI", "MFSL", "SBILIFE"),
    "IT": (
        "COFORGE",
        "HCLTECH",
        "INFY",
        "KPITTECH",
        "LTM",
        "MPHASIS",
        "OFSS",
        "PERSISTENT",
        "SAGILITY",
        "TATAELXSI",
        "TCS",
        "TECHM",
        "WIPRO",
    ),
    "Pharma & Healthcare": (
        "ALKEM",
        "APOLLOHOSP",
        "AUROPHARMA",
        "BIOCON",
        "CIPLA",
        "DIVISLAB",
        "DRREDDY",
        "FORTIS",
        "GLENMARK",
        "LAURUSLABS",
        "LUPIN",
        "MANKIND",
        "MAXHEALTH",
        "SUNPHARMA",
        "TORNTPHARM",
        "ZYDUSLIFE",
    ),
    "Auto": (
        "ASHOKLEY",
        "ATHERENERG",
        "BAJAJ-AUTO",
        "BHARATFORG",
        "BOSCHLTD",
        "EICHERMOT",
        "FORCEMOT",
        "HEROMOTOCO",
        "HYUNDAI",
        "M&M",
        "MARUTI",
        "MOTHERSON",
        "SONACOMS",
        "TIINDIA",
        "TMPV",
        "TVSMOTOR",
        "UNOMINDA",
    ),
    "FMCG": (
        "BRITANNIA",
        "COLPAL",
        "DABUR",
        "GODFRYPHLP",
        "GODREJCP",
        "HINDUNILVR",
        "ITC",
        "MARICO",
        "NESTLEIND",
        "PATANJALI",
        "RADICO",
        "TATACONSUM",
        "UNITDSPR",
        "VBL",
    ),
    "Oil & Gas": ("BPCL", "GAIL", "HINDPETRO", "IOC", "OIL", "ONGC", "PETRONET", "RELIANCE"),
    "Power & Renewables": (
        "ADANIENSOL",
        "ADANIGREEN",
        "ADANIPOWER",
        "INOXWIND",
        "JSWENERGY",
        "NHPC",
        "NTPC",
        "POWERGRID",
        "PREMIERENE",
        "SUZLON",
        "TATAPOWER",
        "WAAREEENER",
    ),
    "Metals & Mining": (
        "COALINDIA",
        "HINDALCO",
        "HINDZINC",
        "JINDALSTEL",
        "JSWSTEEL",
        "NATIONALUM",
        "NMDC",
        "SAIL",
        "TATASTEEL",
        "VEDL",
    ),
    "Capital Goods": (
        "ABB",
        "BHEL",
        "CGPOWER",
        "CUMMINSIND",
        "GVT&D",
        "HAVELLS",
        "KEI",
        "POLYCAB",
        "POWERINDIA",
        "SIEMENS",
        "SOLARINDS",
        "SUPREMEIND",
        "APLAPOLLO",
        "ASTRAL",
    ),
    "Defence & Rail": ("BDL", "BEL", "COCHINSHIP", "HAL", "MAZDOCK", "RVNL"),
    "Cement & Construction": ("AMBUJACEM", "GRASIM", "LT", "NBCC", "SHREECEM", "ULTRACEMCO"),
    "Realty": ("DLF", "GODREJPROP", "LODHA", "OBEROIRLTY", "PHOENIXLTD", "PRESTIGE"),
    "Consumer Durables": (
        "AMBER",
        "ASIANPAINT",
        "BLUESTARCO",
        "CROMPTON",
        "DIXON",
        "KAYNES",
        "KALYANKJIL",
        "PGEL",
        "TITAN",
        "VOLTAS",
    ),
    "Consumer & Retail": (
        "DMART",
        "ETERNAL",
        "INDHOTEL",
        "JUBLFOOD",
        "NAUKRI",
        "NYKAA",
        "PAGEIND",
        "SWIGGY",
        "TRENT",
        "VMM",
    ),
    "Telecom & Media": ("BHARTIARTL", "IDEA", "INDUSTOWER"),
    "Chemicals": ("PIDILITIND", "PIIND", "SRF", "UPL"),
    "Logistics": ("ADANIENT", "ADANIPORTS", "CONCOR", "DELHIVERY", "GMRAIRPORT", "INDIGO"),
}

SECTOR_BY_SYMBOL: dict[str, str] = {
    symbol: sector for sector, symbols in _SECTORS.items() for symbol in symbols
}

OTHER = "Other"


def sector_for(symbol: str) -> str:
    return SECTOR_BY_SYMBOL.get(symbol.upper(), OTHER)


# Fallback universe for the rare morning before any NSE snapshot exists (fresh
# install, or NSE unreachable). Real membership replaces it on the first fetch.
FALLBACK_FO_UNIVERSE: tuple[str, ...] = tuple(sorted(SECTOR_BY_SYMBOL))


def yahoo_symbol(symbol: str) -> str:
    """NSE ticker -> Yahoo Finance ticker (RELIANCE -> RELIANCE.NS)."""
    return f"{symbol.upper()}.NS"
